### ISSUE TITLE
Can't Update Credentials

### ISSUE THREAD

**Issue by juanzilla83** [ganey/unraid-honeygain#2]
Hello, I use Unraid in a daily bases and I saw you new Unraid-Honeygain docker container.

The thing is that I do not know how to "UPDATE ACCOUNT DETAILS IN POST ARGUMENTS". Could you explain how to do it?

Thanks in advance.
JB

**Comment by ganey** [comment]
Hey,

Sorry it's unclear. I'll find a way of making the instructions clearer.



If you enable the advanced view in the top right, then scroll down to the 'Post Arguments' section.

It should have the following:
`-tou-accept -email ACCOUNT_EMAIL -pass ACCOUNT_PASS -device Unraid`

If you put your email and password for HoneyGain in there, the container should then work.


Let me know if you still have any issues 👍

**Comment by juanzilla83** [comment]
Thank you!

Now it's working.

Again, thanks for your work!

**Comment by alaska4life** [comment]
I had the same issue and this resolved it for me.  Quite embarrassed that I've used unraid for almost 5 years and I didn't know about Post Arguments...
